development:
  adapter: postgresql
  encoding: utf8
  database: pennscheduleassembler_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: pennscheduleassembler_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: pennscheduleassembler_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST